apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::968062515286:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-vl19a4lkNIct
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::968062515286:user/suresh
      username: suresh
    # - groups:
    #   - roboshop-trainee
    #   userarn: arn:aws:iam::160885265516:user/john
    #   username: john
    # - groups:
    #   - roboshop-trainee
    #   userarn: arn:aws:iam::160885265516:user/rahim
    #   username: rahim
     - groups:
      - roboshop-admin
      userarn: arn:aws:iam::968062515286:user/ramesh
      username: ramesh
kind: ConfigMap
metadata:
  creationTimestamp: "2026-04-15T02:15:39Z"
  name: aws-auth
  namespace: kube-system
  uid: c25c5f03-f97e-4c87-9758-b22e57880671